version: '3.1'
services:
  stats-server:
    container_name: stats-server-container
    build:
      context: stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=statsdb_user
      - POSTGRES_PASSWORD=baikal4
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=statsdb_user
      - POSTGRES_PASSWORD=baikal4

  ewm-service:
    container_name: ewm-service-container
    build:
      context: main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_USER=ewmdb_user
      - POSTGRES_PASSWORD=baikal4
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewmdb_user
      - POSTGRES_PASSWORD=baikal4
